import { Cartoon } from './types';

// Using placeholder images for demo purposes as original local paths won't work in this environment.
// In a real build, ensure these paths are valid or use URLs.
export const CARTOONS: Cartoon[] = [
  { id: "nu_pogodi", imageUrl: "https://picsum.photos/id/237/800/600", ru: { title: "Ну, погоди!", desc: "Легендарная погоня Волка за Зайцем." }, en: { title: "Well, Just You Wait!", desc: "Legendary chase of the Wolf after the Hare." }, tr: { title: "Seni Gidi Seni!", desc: "Kurt'un Tavşan'ı efsanevi kovalamacası." } },
  { id: "vinni", imageUrl: "https://picsum.photos/id/1025/800/600", ru: { title: "Винни-Пух", desc: "Винни-Пуха озвучивал Евгений Леонов." }, en: { title: "Winnie-the-Pooh", desc: "Soviet version of the famous bear." }, tr: { title: "Winnie-the-Pooh", desc: "Ünlü ayının Sovyet versiyonu." } },
  { id: "prostokvashino", imageUrl: "https://picsum.photos/id/1074/800/600", ru: { title: "Простоквашино", desc: "Дядя Фёдор уехал жить с котом и псом." }, en: { title: "Prostokvashino", desc: "A boy lives in a village with a cat and a dog." }, tr: { title: "Prostokvaşino", desc: "Bir çocuk köyde kedi ve köpekle yaşar." } },
  { id: "bremenskie", imageUrl: "https://picsum.photos/id/1084/800/600", ru: { title: "Бременские музыканты", desc: "Музыкальная фантазия с элементами рок-н-ролла." }, en: { title: "Bremen Musicians", desc: "Musical fantasy with rock-n-roll elements." }, tr: { title: "Bremen Mızıkacıları", desc: "Rock-n-roll öğeleri içeren müzikal fantezi." } },
  { id: "ezhik", imageUrl: "https://picsum.photos/id/16/800/600", ru: { title: "Ёжик в тумане", desc: "Признан лучшим мультфильмом всех времён." }, en: { title: "Hedgehog in the Fog", desc: "Acclaimed as the best cartoon of all time." }, tr: { title: "Sisteki Kirpi", desc: "Tüm zamanların en iyi çizgi filmi seçildi." } },
  { id: "karlson", imageUrl: "https://picsum.photos/id/177/800/600", ru: { title: "Малыш и Карлсон", desc: "История о человеке, который живет на крыше." }, en: { title: "Kid and Karlsson", desc: "Story about a man who lives on the roof." }, tr: { title: "Çocuk ve Karlsson", desc: "Çatıda yaşayan bir adamın hikayesi." } },
  { id: "pes", imageUrl: "https://picsum.photos/id/200/800/600", ru: { title: "Жил-был пёс", desc: "Фраза «Щас спою!» стала крылатой." }, en: { title: "Once Upon a Dog", desc: "The phrase 'I'll sing now!' became legendary." }, tr: { title: "Bir Zamanlar Bir Köpek", desc: "'Şimdi şarkı söyleyeceğim!' efsane oldu." } },
  { id: "taina", imageUrl: "https://picsum.photos/id/219/800/600", ru: { title: "Тайна третьей планеты", desc: "Фантастическое путешествие Алисы Селезнёвой." }, en: { title: "Mystery of the Third Planet", desc: "Sci-fi adventure of Alice Selezneva." }, tr: { title: "Üçüncü Gezegenin Sırrı", desc: "Alice Selezneva'nın bilim kurgu macerası." } },
  { id: "korabl", imageUrl: "https://picsum.photos/id/238/800/600", ru: { title: "Летучий корабль", desc: "Мюзикл про любовь и летучий корабль." }, en: { title: "The Flying Ship", desc: "Musical about love and a flying ship." }, tr: { title: "Uçan Gemi", desc: "Aşk ve uçan gemi hakkında müzikal." } },
  { id: "gena", imageUrl: "https://picsum.photos/id/240/800/600", ru: { title: "Крокодил Гена", desc: "Здесь впервые прозвучала песня про день рождения." }, en: { title: "Gena the Crocodile", desc: "First appearance of the famous birthday song." }, tr: { title: "Timsah Gena", desc: "Ünlü doğum günü şarkısının ilk çıkışı." } },
  { id: "leopold", imageUrl: "https://picsum.photos/id/257/800/600", ru: { title: "Кот Леопольд", desc: "Ребята, давайте жить дружно!" }, en: { title: "Leopold the Cat", desc: "Guys, let's live friendly!" }, tr: { title: "Kedi Leopold", desc: "Çocuklar, dostça yaşayalım!" } },
  { id: "kesha", imageUrl: "https://picsum.photos/id/259/800/600", ru: { title: "Попугай Кеша", desc: "Таити, Таити... Нас и здесь неплохо кормят!" }, en: { title: "Parrot Kesha", desc: "Tahiti, Tahiti... We are fed well here too!" }, tr: { title: "Papağan Kesha", desc: "Tahiti, Tahiti... Burada da iyi besleniyoruz!" } },
  { id: "sneg", imageUrl: "https://picsum.photos/id/275/800/600", ru: { title: "Падал прошлогодний снег", desc: "Маловато будет!" }, en: { title: "Last Year's Snow Was Falling", desc: "It won't be enough!" }, tr: { title: "Geçen Yılın Karı Yağıyordu", desc: "Bu yetmeyecek!" } },
  { id: "umka", imageUrl: "https://picsum.photos/id/287/800/600", ru: { title: "Умка", desc: "История о белом медвежонке." }, en: { title: "Umka", desc: "Story about a polar bear cub." }, tr: { title: "Umka", desc: "Kutup ayısı yavrusu hakkında hikaye." } },
  { id: "maugli", imageUrl: "https://picsum.photos/id/296/800/600", ru: { title: "Маугли", desc: "Советская экранизация Киплинга." }, en: { title: "Mowgli", desc: "Soviet adaptation of Kipling." }, tr: { title: "Mowgli", desc: "Kipling'in Sovyet uyarlaması." } },
  { id: "cheburashka", imageUrl: "https://picsum.photos/id/301/800/600", ru: { title: "Чебурашка", desc: "Неизвестный науке зверь с большими ушами." }, en: { title: "Cheburashka", desc: "A creature unknown to science with big ears." }, tr: { title: "Cheburashka", desc: "Bilimin tanımadığı büyük kulaklı bir yaratık." } },
  { id: "vovka", imageUrl: "https://picsum.photos/id/338/800/600", ru: { title: "Вовка в Тридевятом царстве", desc: "«И так сойдёт!» — девиз лентяя Вовки." }, en: { title: "Vovka in the Far Far Away Kingdom", desc: "'Good enough!' is the motto of lazy Vovka." }, tr: { title: "Vovka Uzak Krallıkta", desc: "'Böyle de olur!' tembel Vovka'nın sloganıdır." } },
  { id: "popugaev", imageUrl: "https://picsum.photos/id/357/800/600", ru: { title: "38 попугаев", desc: "А в попугаях-то я гораздо длиннее!" }, en: { title: "38 Parrots", desc: "I am much longer in parrots!" }, tr: { title: "38 Papağan", desc: "Papağanlarla ölçülünce çok daha uzunum!" } },
  { id: "kuzya", imageUrl: "https://picsum.photos/id/364/800/600", ru: { title: "Домовёнок Кузя", desc: "Я не жадный, я домовитый!" }, en: { title: "Kuzya the Brownie", desc: "I am not greedy, I am thrifty!" }, tr: { title: "Ev Cini Kuzya", desc: "Cimri değilim, tutumluyum!" } },
  { id: "funtik", imageUrl: "https://picsum.photos/id/366/800/600", ru: { title: "Приключения Фунтика", desc: "Подайте на домики для бездомных поросят!" }, en: { title: "Adventures of Funtik", desc: "Donate for houses for homeless piglets!" }, tr: { title: "Funtik'in Maceraları", desc: "Evsiz domuz yavruları için bağış yapın!" } },
  { id: "gav", imageUrl: "https://picsum.photos/id/395/800/600", ru: { title: "Котёнок по имени Гав", desc: "Давай бояться вместе!" }, en: { title: "A Kitten Named Woof", desc: "Let's be afraid together!" }, tr: { title: "Hav Adında Bir Yavru Kedi", desc: "Birlikte korkalım!" } },
  { id: "ostrov", imageUrl: "https://picsum.photos/id/403/800/600", ru: { title: "Остров сокровищ", desc: "Гротескная экранизация с музыкальными вставками." }, en: { title: "Treasure Island", desc: "Grotesque adaptation with musical interludes." }, tr: { title: "Define Adası", desc: "Müzikal bölümleri olan grotesk bir uyarlama." } },
  { id: "varezhka", imageUrl: "https://picsum.photos/id/433/800/600", ru: { title: "Варежка", desc: "Девочка так хотела собаку, что варежка ожила." }, en: { title: "The Mitten", desc: "A girl wanted a dog so much that her mitten came to life." }, tr: { title: "Eldiven", desc: "Kız o kadar çok köpek istedi ki eldiveni canlandı." } },
  { id: "ded_moroz", imageUrl: "https://picsum.photos/id/450/800/600", ru: { title: "Дед Мороз и лето", desc: "Дед Мороз узнает, что такое лето." }, en: { title: "Father Frost and Summer", desc: "Santa Claus finds out what summer is." }, tr: { title: "Ded Moroz ve Yaz", desc: "Noel Baba yazın ne olduğunu öğrenir." } },
  { id: "chipollino", imageUrl: "https://picsum.photos/id/454/800/600", ru: { title: "Чиполлино", desc: "Революция овощей против синьора Помидора." }, en: { title: "Chipollino", desc: "Vegetable revolution against Signor Tomato." }, tr: { title: "Cipollino", desc: "Sinyor Domates'e karşı sebze devrimi." } },
  { id: "antelopa", imageUrl: "https://picsum.photos/id/465/800/600", ru: { title: "Золотая антилопа", desc: "Антилопа выбивала золотые монеты копытами." }, en: { title: "The Golden Antelope", desc: "The antelope struck gold coins with its hooves." }, tr: { title: "Altın Antilop", desc: "Antilop toynaklarıyla altın para basıyordu." } },
  { id: "alenkiy", imageUrl: "https://picsum.photos/id/493/800/600", ru: { title: "Аленький цветочек", desc: "Сказка о любви красавицы и чудовища." }, en: { title: "The Scarlet Flower", desc: "A fairy tale about the love of beauty and the beast." }, tr: { title: "Kızıl Çiçek", desc: "Güzel ve Çirkin'in aşkını anlatan bir masal." } }
];

export const TRANSLATIONS = {
    ru: { title: "СоюзМультКвиз", subtitle: "МУЛЬТФИЛЬМЫ СССР", start: "НАЧАТЬ", shop: "МАГАЗИН", score: "СЧЕТ", level: "УРОВЕНЬ", record: "РЕКОРД", stars: "ЗВЕЗДЫ", question: "ОТКУДА ЭТОТ КАДР?", frame_label: "КАДР ИЗ МУЛЬТФИЛЬМА", next: "ДАЛЕЕ", correct: "ВЕРНО!", wrong: "ОШИБКА!", gameover: "КОНЕЦ ФИЛЬМА", your_score: "ВАШ РЕЗУЛЬТАТ", gameover_msg: "Плёнка оборвалась! Но вы можете склеить её.", revive: "ВОСКРЕСНУТЬ (+1 ❤)", ad_hint: "Смотреть рекламу", menu: "В МЕНЮ", resume: "ПРОДОЛЖИТЬ", pause: "ПАУЗА", shop_title: "ЛАВКА", shop_msg: "Здесь скоро появятся новые товары!", tv_brand: "РУБИН" },
    en: { title: "SovietToonQuiz", subtitle: "USSR CARTOONS", start: "START", shop: "SHOP", score: "SCORE", level: "LEVEL", record: "BEST", stars: "STARS", question: "GUESS THE CARTOON", frame_label: "SCENE FROM CARTOON", next: "NEXT", correct: "CORRECT!", wrong: "WRONG!", gameover: "THE END", your_score: "YOUR SCORE", gameover_msg: "The film broke! But you can fix it.", revive: "REVIVE (+1 ❤)", ad_hint: "Watch Ad", menu: "MENU", resume: "RESUME", pause: "PAUSED", shop_title: "STORE", shop_msg: "New items coming soon!", tv_brand: "RUBIN" },
    tr: { title: "SovyetÇizgiQuiz", subtitle: "SSCB ÇİZGİ FİLMLERİ", start: "BAŞLA", shop: "MAĞAZA", score: "PUAN", level: "SEVİYE", record: "REKOR", stars: "YILDIZLAR", question: "HANGİ ÇİZGİ FİLM?", frame_label: "ÇİZGİ FİLMDEN KARE", next: "SONRAKİ", correct: "DOĞRU!", wrong: "YANLIŞ!", gameover: "FİLMİN SONU", your_score: "PUANINIZ", gameover_msg: "Film koptu! Ama tamir edebilirsin.", revive: "CANLAN (+1 ❤)", ad_hint: "Reklam izle", menu: "MENÜ", resume: "DEVAM", pause: "DURAKLATILDI", shop_title: "DÜKKAN", shop_msg: "Yeni ürünler yakında!", tv_brand: "RUBIN" }
};